### ISSUE TITLE
Key Error Progress

### ISSUE THREAD

**Issue by jletienne** [dblume/overcast-podcast-activity-feed#3]
I'm getting an error saying progress isn't a key in ep.attrib

<img width="380" alt="Screen Shot 2020-12-03 at 8 17 54 PM" src="https://user-images.githubusercontent.com/10469138/101113339-c91d9580-35a4-11eb-899a-6f8675e119b6.png">

**Comment by jletienne** [comment]
Better picture

<img width="777" alt="image" src="https://user-images.githubusercontent.com/10469138/101113639-71cbf500-35a5-11eb-8d66-b590fa77fd9c.png">

**Comment by jletienne** [comment]
Played Episodes Don't Have a Progress field... I added a try/except on line 122 but I wish there was a way to figure out how long the episode was

<img width="675" alt="image" src="https://user-images.githubusercontent.com/10469138/101116095-10f2eb80-35aa-11eb-9f22-872a64b47c8c.png">

**Comment by dblume** [comment]
Overcast says they don't indicate duration because of dynamic ad insertion. See this twitter thread: https://twitter.com/dblume/status/1206287574869790720
